api = "0.2"

[buildpack]
  id = "oscarnevarezleal/gh-buildpack"
  name = "gh-buildpack"
  version = "0.0.1"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]

  default_version = "0.0.1"
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/package.sh"

  [metadata.default-versions]
    blueprintgen = "1.14.0"

  [[metadata.dependencies]]
    id = "gh"
    version = "1.14.0"
    name = "gh"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/cli/cli/archive/refs/tags/v1.14.0.tar.gz"
    sha256 = "1a99050644b4821477aabc7642bbcae8a19b3191e9227cd8078016d78cdd83ac"
    source = "https://github.com/cli/cli/archive/refs/tags/v1.14.0.tar.gz"
    source_sha256 = "1a99050644b4821477aabc7642bbcae8a19b3191e9227cd8078016d78cdd83ac"